### ISSUE TITLE
Parse compressed content

### ISSUE THREAD

**Issue by wendigo** [tdewolff/push#2]
In current version of ```push``` parsers do not recognize compressed content (gzip or brotli) and error "unexpected null/character" is returned in most of the cases

**Comment by tdewolff** [comment]
Thanks for the bug reports, I will look at them shortly.

**Comment by mholt** [comment]
Would this involve having to decompress them, parse, and re-compress them? I'm wondering if compressed content should just stay compressed, for performance' sake.

**Comment by tdewolff** [comment]
`push` assumes an uncompressed input, so you'll need to uncompress this yourself. What is the use case here? Perhaps I'd understand the problem you're solving better if I know what it is about.

@mholt I suppose yes. But if the list of resources is kept in a cache than a one time decompression/recompression is a fine compromise I think. Besides, maybe you could use a TeeReader so that the compressed content stays, but is decompressed and then parsed on the side by a goroutine.

**Comment by mholt** [comment]
Yeah, I agree with you, in that I don't think the job of the push package should be to decompress content.

**Comment by wendigo** [comment]
@tdewolff use case is quite simple: integrate your library with Caddy :) Caddy itself has gzip plugin which compresses content in the fly and also has feature to serve pre-compressed files. Therefore most of the content server to the end user is compressed.

**Comment by mholt** [comment]
@tdewolff Like I said elsewhere, though, I think we can get a handle on the content before it's compressed by wrapping the responseWriter.
